-- PollApp Supabase setup

create table if not exists public."surveyDetail" (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  deadline date,
  category text not null,
  created_at timestamptz not null default now()
);

alter table public."surveyDetail" alter column deadline drop not null;

create table if not exists public."questionDetail" (
  id bigint generated by default as identity primary key,
  survey bigint not null references public."surveyDetail"(id) on delete cascade,
  question text not null,
  "allowMultipleAnswers" boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public."answerDetail" (
  id bigint generated by default as identity primary key,
  question bigint not null references public."questionDetail"(id) on delete cascade,
  answer text not null,
  created_at timestamptz not null default now()
);

create table if not exists public."choosenDetail" (
  id bigint generated by default as identity primary key,
  survey_id bigint not null references public."surveyDetail"(id) on delete cascade,
  question_id bigint not null references public."questionDetail"(id) on delete cascade,
  answer_id bigint not null references public."answerDetail"(id) on delete cascade,
  submission_id uuid not null,
  created_at timestamptz not null default now()
);

alter table public."surveyDetail" enable row level security;
alter table public."questionDetail" enable row level security;
alter table public."answerDetail" enable row level security;
alter table public."choosenDetail" enable row level security;

drop policy if exists "Public can read surveys" on public."surveyDetail";
create policy "Public can read surveys"
on public."surveyDetail" for select
to anon, authenticated
using (true);

drop policy if exists "Public can create surveys" on public."surveyDetail";
create policy "Public can create surveys"
on public."surveyDetail" for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can read questions" on public."questionDetail";
create policy "Public can read questions"
on public."questionDetail" for select
to anon, authenticated
using (true);

drop policy if exists "Public can create questions" on public."questionDetail";
create policy "Public can create questions"
on public."questionDetail" for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can read answers" on public."answerDetail";
create policy "Public can read answers"
on public."answerDetail" for select
to anon, authenticated
using (true);

drop policy if exists "Public can create answers" on public."answerDetail";
create policy "Public can create answers"
on public."answerDetail" for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can read votes" on public."choosenDetail";
create policy "Public can read votes"
on public."choosenDetail" for select
to anon, authenticated
using (true);

drop policy if exists "Public can submit votes" on public."choosenDetail";
create policy "Public can submit votes"
on public."choosenDetail" for insert
to anon, authenticated
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'surveyDetail'
  ) then
    alter publication supabase_realtime add table public."surveyDetail";
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'choosenDetail'
  ) then
    alter publication supabase_realtime add table public."choosenDetail";
  end if;
end
$$;
